name: Server CI

on:
  push:
    branches:
      - master
    paths:
      - "server/**"
  pull_request:
    branches:
      - master
    paths:
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # Recommended stable version

      - name: Enable Corepack
        run: corepack enable

      - name: Use correct Yarn version
        run: corepack prepare yarn@4.9.1 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build server
        run: yarn build
