name: Server CI

on:
  push:
    branches:
      - master
    paths:
      - "server/**"
  pull_request:
    branches:
      - master
    paths:
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Build server
        run: yarn build
